# -*- coding: utf-8 -*-
"""dipt-10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dLYNSKnTEQ440Irv4KoFZiVdL8yAiAGd
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow

# Create the Text using cv2.putText
img = np.zeros((300, 600), dtype='uint8')
font = cv2.FONT_ITALIC
cv2.putText(img, "Hanshika", (5, 150), font, 3, (255), 5, cv2.LINE_AA)
cv2_imshow(img)
cv2.waitKey(0)

# Create the structuring element
kernel_open = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
kernel_close = cv2.getStructuringElement(cv2.MORPH_RECT, (11, 11))

# Use Opening operation
opened = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel_open)
cv2_imshow(opened)
cv2.waitKey(0)

# Use Closing Operation
closed = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel_close)
cv2_imshow(closed)
cv2.waitKey(0)

